# Vectors and Matrices in Numpy - Lab

## Introduction

In this lab, you'll solve some simple matrix creation and manipulation exercises based on what you've learned so far in this section. The key takeaway here is to be able to understand how to use indexing with matrices and vectors while applying some basic operations.

## Objectives
You will be able to:
* Define vectors and matrices in NumPy
* Check the shape of vectors and matrices
* Access and manipulate individual scalar components of a matrix. 

## 1. Define two arrays $A$  with shape $ (4 \times 2)$ and $B$ with shape $(2 \times 3)$ 
So    $A =    
  \left[ {\begin{array}{cc}
   1402 & 191 \\
   1371 &  821\\
   949 &  1437 \\
   147 & 1448 \\
  \end{array} }\right]
$
and
$
B =    
  \left[ {\begin{array}{ccc}
   1 & 2 & 3 \\
   4 & 5 & 6\\
  \end{array} }\right]
$

In [4]:
import numpy as np
# Code Here
A = np.array([[1402, 191],
              [1371, 821],
              [ 949, 1437],
              [ 147, 1448]])
B = np.array([[1, 2, 3],
              [4, 5, 6]])
print(A)
print(B)

[[1402  191]
 [1371  821]
 [ 949 1437]
 [ 147 1448]]
[[1 2 3]
 [4 5 6]]


## 2. Print the dimensions of $A$ and $B$ 

In [5]:
# Code Here
print(A.shape)
print(B.shape)

(4, 2)
(2, 3)


## 3. Print some of the elements from $A$: 
* first row and first column
* first row and second column
* third row and second column
* fourth row and first column

In [11]:
# Code Here
A[0,0]

1402

In [12]:
A[0,1]

191

In [13]:
A[2,1]

1437

In [14]:
A[3,0]

147

## 4. Write a routine to populate a matrix with random data
* Create an $(3 \times 3)$ Numpy array with all zeros (use `np.zeros()`)
* Access each location $(i,j)$ of this matrix and fill in random values between the range 1 and 10. 

In [17]:
# Code Here (due to random data , your output might be different)
my_array = np.zeros((3,3))
my_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
dimensions = my_array.shape

for row in range(dimensions[0]):
    for col in range(dimensions[1]):
        my_array[row,col] = np.random.random_integers(1,10)
my_array

/Users/dennistrimarchi/anaconda3/envs/learn-env/lib/python3.6/site-packages/ipykernel_launcher.py:5: DeprecationWarning: This function is deprecated. Please call randint(1, 10 + 1) instead
  """


array([[ 9.,  1.,  6.],
       [ 7.,  6.,  5.],
       [ 3., 10., 10.]])

## 5. Turn the above routine into a function
* Create two $(4 \times 4)$ zero valued matrices and fill with random data using the function
* Add the matrices together in numpy 
* Show the results

In [23]:
def get_random_matrix(matrix):
    dimensions = matrix.shape
    for row in range(dimensions[0]):
        for col in range(dimensions[1]):
            matrix[row,col] = np.random.random_integers(1,10)
    return matrix

In [26]:
# Code Here (due to random data , your output might be different)
A = get_random_matrix(np.zeros((4,4)))
B = get_random_matrix(np.zeros((4,4)))
print(A)
print(B)

print("A + B")
A+B

[[9. 7. 3. 9.]
 [5. 6. 7. 9.]
 [9. 7. 9. 9.]
 [5. 4. 2. 5.]]
[[ 6.  7.  2.  5.]
 [ 5.  9.  5.  3.]
 [ 8.  8.  6. 10.]
 [ 4.  8.  3.  5.]]
A + B


/Users/dennistrimarchi/anaconda3/envs/learn-env/lib/python3.6/site-packages/ipykernel_launcher.py:5: DeprecationWarning: This function is deprecated. Please call randint(1, 10 + 1) instead
  """


array([[15., 14.,  5., 14.],
       [10., 15., 12., 12.],
       [17., 15., 15., 19.],
       [ 9., 12.,  5., 10.]])

## Summary 

In this lab, we saw how to create and manipulate vectors and matrices in numpy. We shall now move forward to learning more complex operations including dot products and inverses. 